### ISSUE TITLE
 Implement a database design with create and update scripts

### ISSUE THREAD

**Issue by jamesfernando94** [Gregam3/ASEGroup1#19]
- Create a desgin for the database possibly using https://www.mysql.com/products/workbench/
- Get the desgin approved by the others in the group
- Create folder structure in the repo for the database create and update scripts
- Implement create scripts for the database 
-ssh into database on AWS server and run create scripts

**Comment by richousrick** [comment]
![Initial Database Design](https://user-images.githubusercontent.com/5024935/47371391-a0492780-d6df-11e8-9e32-c6799d8efccf.png)

**Comment by jamesfernando94** [comment]
Could you add the data types for the fields

**Comment by richousrick** [comment]
![Revised Database Design](https://user-images.githubusercontent.com/5024935/47375434-27020280-d6e8-11e8-9441-ea993e4a2fac.png)
