### ISSUE TITLE
Set up generic components and integrate hibernate

### ISSUE THREAD

**Issue by Gregam3** [Gregam3/ASEGroup1#28]
Hibernate is a tool that automatically maps the Java model to the database. 

Combining this #30 as it is necessary for testing.

Dependant on #19.

**Comment by jamesfernando94** [comment]
So I'm currently working on #22, should I create a wrapper class for this to implement or should I add this as a dependency to #22?

**Comment by jamesfernando94** [comment]
> Combining this #28 as it is necessary for testing.

@Gregam3 did you mean #30 and should I close that as it is a part of this now?

**Comment by Gregam3** [comment]
I did, I'll change it now.
