### ISSUE TITLE
Pre-commit script bug

### ISSUE THREAD

**Issue by Gregam3** [Gregam3/ASEGroup1#34]
Caused

 `//Can easily be customised here https://mapstyle.withgoogle.com/, dump generated JSON in array` 

to turn into:

`/ /
                Can easily be customised here https:
                    // mapstyle.withgoogle.com/, dump generated JSON in array`

**Comment by Gregam3** [comment]
It also appears to have completely changed the JSX in the React making it much less readable
![image](https://user-images.githubusercontent.com/14945621/47447321-1d929c00-d7b5-11e8-8e02-0a48321beed6.png)

**Comment by jamesfernando94** [comment]
## Planning

- [ ] Remove javascript files from pre-commit formatting
- [ ] Make sure that it doesn't adversely affect the java code
- [ ] Add fixes for javascript code
