### ISSUE TITLE
When a marker is touched create pop-up 

### ISSUE THREAD

**Issue by Gregam3** [Gregam3/ASEGroup1#73]
The pop-up should contain:
-address
-Price sold
-Post code
(maybe full address)

**Comment by JoshHasan590** [comment]
Built in feature of MapView.Marker
Simply requires the title and description properties (of MapView Markers) to be set to the real address and price

**Comment by JoshHasan590** [comment]
- [ ] Decide as a group which property set as address or price. e.g: title = price, description = address or vice versa
