### ISSUE TITLE
Implement Expo.Location.watchPositionAsync(options, callback) in Mobile application

### ISSUE THREAD

**Issue by jamesfernando94** [Gregam3/ASEGroup1#9]
https://docs.expo.io/versions/latest/sdk/location#expolocationwatchpositionasyncoptions-callback App.js

**Comment by richousrick** [comment]
Is this still needed?

**Comment by jamesfernando94** [comment]
@richousrick I believe so as I was getting the bug where if a location wasn't returned it would stop polling for new locations after a bit.
